### ISSUE TITLE
PHP Warning: Undefined array key 2 in Classes/Service/AssetService.php

### ISSUE THREAD

**Issue by sdelcroix** [FluidTYPO3/vhs#1853]
Hi,

In the CSS file that I'm including with v:asset.style, there are paths for fonts files as follow :

```CSS
@font-face{
    font-family:weathericons;
    src:url(../font/weathericons-regular-webfont.eot);
    src:url(../font/weathericons-regular-webfont.eot?#iefix) format('embedded-opentype'),url(../font/weathericons-regular-webfont.woff2) format('woff2'),url(../font/weathericons-regular-webfont.woff) format('woff'),url(../font/weathericons-regular-webfont.ttf) format('truetype'),url(../font/weathericons-regular-webfont.svg#weather_iconsregular) format('svg');
    font-weight:400;
    font-style:normal
}
```

A PHP Warning is raised in AssertService when there's no suffix in the path. The "Undefined array key 2" error occurs with the "list" function at FluidTYPO3\Vhs\Service\AssetService->copyReferencedFilesAndReplacePaths() :

```PHP
                if (0 < preg_match('/([^\?#]+)(.+)?/', $match, $items)) {
                    list(, $path, $suffix) = $items;
                } else {
                    $path = $match;
                    $suffix = '';
                }
```
The test for the regexp shouldn't be inverted ? Like this
```PHP
if (0 < preg_match('/([^\?#]+)(.+)?/', $match, $items)) {
                    $path = $match;
                    $suffix = '';
                } else {
                    list(, $path, $suffix) = $items;
                }
```
Or the regexp may be changed like this :
```PHP
if (0 < preg_match('/([^\?#]+)(#.+)/', $match, $items)) {
```
Because in the actual state, it captures only paths without prefix.
