### ISSUE TITLE
<v:asset.script  and <v:asset.style

### ISSUE THREAD

**Issue by franzbrandtwein** [FluidTYPO3/vhs#655]
both do not replace fluid variables after the first braces. e.g.

``` css
<v:asset.style name="SliderCss" group="template" fluid="1" arguments="" trim="1" namedChunks="0">
  .{FLUIDVAR}CLASSNAME
  {
    border: 0;
  }
</v:asset.style>
```

is working. {FLUIDVAR} is replaced by the variable value passed to the partial

``` css
<v:asset.style name="SliderCss" group="template" fluid="1" arguments="" trim="1" namedChunks="0">
  .CLASSNAME
  {
    border: {FLUIDVAR};
  }
</v:asset.style>
```

is not working.
